/*
Copyright (c) 2024 OpenInfra Foundation Europe

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/lioneljouin/meridio-experiment/apis/v1alpha1"
	scheme "github.com/lioneljouin/meridio-experiment/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayRoutersGetter has a method to return a GatewayRouterInterface.
// A group's client should implement this interface.
type GatewayRoutersGetter interface {
	GatewayRouters(namespace string) GatewayRouterInterface
}

// GatewayRouterInterface has methods to work with GatewayRouter resources.
type GatewayRouterInterface interface {
	Create(ctx context.Context, gatewayRouter *v1alpha1.GatewayRouter, opts v1.CreateOptions) (*v1alpha1.GatewayRouter, error)
	Update(ctx context.Context, gatewayRouter *v1alpha1.GatewayRouter, opts v1.UpdateOptions) (*v1alpha1.GatewayRouter, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayRouter *v1alpha1.GatewayRouter, opts v1.UpdateOptions) (*v1alpha1.GatewayRouter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GatewayRouter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GatewayRouterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GatewayRouter, err error)
	GatewayRouterExpansion
}

// gatewayRouters implements GatewayRouterInterface
type gatewayRouters struct {
	*gentype.ClientWithList[*v1alpha1.GatewayRouter, *v1alpha1.GatewayRouterList]
}

// newGatewayRouters returns a GatewayRouters
func newGatewayRouters(c *MeridioV1alpha1Client, namespace string) *gatewayRouters {
	return &gatewayRouters{
		gentype.NewClientWithList[*v1alpha1.GatewayRouter, *v1alpha1.GatewayRouterList](
			"gatewayrouters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.GatewayRouter { return &v1alpha1.GatewayRouter{} },
			func() *v1alpha1.GatewayRouterList { return &v1alpha1.GatewayRouterList{} }),
	}
}
